### ISSUE TITLE
How to specify `InvokeMode: RESPONSE_STREAM` for the lambda?

### ISSUE THREAD

**Issue by olizilla** [web3-storage/autobahn#8]
This is required to allow streaming responses when invoking the lambda via the function url.

We've set this manually in the aws console for now, but it's not obvious how we set it explicitly in the infra code.

see: https://aws.amazon.com/blogs/compute/introducing-aws-lambda-response-streaming/

**Comment by alanshaw** [comment]
Tumbleweeds on the discord https://discord.com/channels/983865673656705025/1083422760111439973/threads/1111244380884451389

To be fair it's 1 month old and CDK does not expose an API for it yet.

**Comment by alanshaw** [comment]
resolved by https://github.com/web3-storage/autobahn/pull/13
